/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module control_3 (
    input clk,
    input rst,
    output reg [3:0] rowOut,
    output reg [6:0] colOut
  );
  
  
  
  reg [3:0] M_row_d, M_row_q = 1'h0;
  
  reg [6:0] M_col_d, M_col_q = 1'h0;
  
  always @* begin
    M_col_d = M_col_q;
    M_row_d = M_row_q;
    
    M_row_d = M_row_q;
    M_col_d = M_col_q;
    if (M_col_q >= 7'h50) begin
      M_col_d = 1'h0;
      M_row_d = M_row_q + 1'h1;
    end else begin
      M_col_d = M_col_q + 1'h1;
    end
    rowOut = M_row_q;
    colOut = M_col_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_col_q <= 1'h0;
    end else begin
      M_col_q <= M_col_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_row_q <= 1'h0;
    end else begin
      M_row_q <= M_row_d;
    end
  end
  
endmodule
