/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module random_4 (
    input clk,
    input rst,
    output reg [6:0] randrow,
    output reg [6:0] randcol
  );
  
  
  
  reg [5:0] M_randr_d, M_randr_q = 1'h0;
  
  reg [5:0] M_randc_d, M_randc_q = 1'h0;
  
  integer count;
  
  always @* begin
    M_randc_d = M_randc_q;
    M_randr_d = M_randr_q;
    
    M_randr_d = M_randr_q;
    M_randc_d = M_randc_q;
    for (count = 4'ha; count > 1'h0; count = count - 1) begin
      if ((M_randr_q + 2'h3) - count * ((M_randr_q + 2'h3) / 5'h1e) + 1'h1 < 5'h1f) begin
        M_randr_d = (M_randr_q + 2'h3) - count * ((M_randr_q + 2'h3) / 5'h1e) + 1'h1;
      end
      if ((M_randc_q + 3'h5) - count * ((M_randc_q + 3'h5) / 5'h1e) + 5'h11 < 6'h2f) begin
        M_randc_d = (M_randc_q + 3'h5) - count * ((M_randc_q + 3'h5) / 5'h1e) + 5'h11;
      end
    end
    randrow = M_randr_q;
    randcol = M_randc_q;
  end
  
  always @(posedge clk) begin
    M_randc_q <= M_randc_d;
  end
  
  
  always @(posedge clk) begin
    M_randr_q <= M_randr_d;
  end
  
endmodule
